/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package botfilter determines whether a GitHub user/author is a bot or
// auto-generated account.
//
// Rules mirror the isAutogenerated() / isBotReview() JS functions used in the
// n8n code-nodes.  The github-actions[bot] "conditional AI" path in the JS was
// effectively a no-op (the legacy `includes('github-actions')` always caught
// it), so we keep the logic simple: any name matching the patterns is a bot.
package botfilter

import "strings"

// IsBot returns true when name indicates a bot or auto-generated account.
// It is used both for PR authors and for review-comment authors.
func IsBot(name, _, _ string) bool {
	if name == "" {
		return true
	}
	lower := strings.ToLower(name)

	return strings.Contains(lower, "[bot]") ||
		strings.Contains(lower, "copilot") ||
		strings.Contains(lower, "github-actions") ||
		strings.Contains(lower, "github actions") ||
		strings.Contains(lower, "dependabot") ||
		strings.Contains(lower, "red-hat-konflux") ||
		strings.Contains(lower, "renovate") ||
		strings.Contains(lower, "fullsend-ai") ||
		strings.Contains(lower, "snyk") ||
		lower == "ci-operator" ||
		lower == "rh-tap-build-team" ||
		strings.HasSuffix(lower, "-bot") ||
		strings.HasSuffix(lower, "-robot") ||
		isProjectGroupBot(lower)
}

// isProjectGroupBot matches the pattern ^(project|group)_\d+_bot.
func isProjectGroupBot(lower string) bool {
	for _, prefix := range []string{"project_", "group_"} {
		if !strings.HasPrefix(lower, prefix) {
			continue
		}
		rest := lower[len(prefix):]
		i := 0
		for i < len(rest) && rest[i] >= '0' && rest[i] <= '9' {
			i++
		}
		if i > 0 && strings.HasPrefix(rest[i:], "_bot") {
			return true
		}
	}
	return false
}
